### ISSUE TITLE
Docker workaround not strictly required for Docker 1.13+

### ISSUE THREAD

**Issue by TimWolla** [Tarsnap/spiped#113]
I just wanted to let you know that the Docker workaround is not strictly required for Docker 1.13 any more. However it is necessary to pass a special flag to Docker in order to spawn an extra init process. See this PR in the repository for the documentation to the official Docker images for extra information: https://github.com/docker-library/docs/pull/814

I'll leave it up to you whether you want to remove the workaround or not.

**Comment by cperciva** [comment]
My general bias is in favour of keeping workarounds in place for as long as we can imagine people reasonably using older systems.  I don't know how quick people are to upgrade to new versions of Docker, but it seems like "you need to upgrade and pass a special flag" is enough of a hurdle that it's likely there are users who would trip over this issue otherwise.

**Comment by cperciva** [comment]
I'm going to close this issue, since there doesn't seem to be anything which needs to be done here; if the workaround starts causing problems, or if enough time passes that it's clearly no longer useful, we can revisit it.
