### ISSUE TITLE
Make fails on Slackware64 Linux 14.2

### ISSUE THREAD

**Issue by zoot** [Tarsnap/spiped#127]
Hello

An attempt to build fails as follows:
```
$ make
Makefile:5: *** missing separator.  Stop.
```
I've seen [this](http://stackoverflow.com/questions/16931770/makefile4-missing-separator-stop/42195571#42195571) post on stackoverflow.com regarding tabs, but cannot figure out what may be causing this failure. There don't seem to be any missing tabs for any actions.

The system has `GNU Make 4.1` installed.

Please let me know if you require more info to debug this.

Thanks.

**Comment by cperciva** [comment]
I have no idea how this is possible.  Line 5 of Makefile isn't even part of a build recipe.

Are you sure that your checked-out tree hasn't been mangled somehow?  What's on line 5 of Makefile?

**Comment by zoot** [comment]
Line 5 is `.for D in ${PROGS}`

```
$ head -7 Makefile
PKG=	spiped
PROGS=	spiped spipe
PUBLISH= ${PROGS} BUILDING CHANGELOG COPYRIGHT README STYLE POSIX lib libcperciva proto

.for D in ${PROGS}
${PKG}-${VERSION}/${D}/Makefile:
	echo '.POSIX:' > $@
```

Here's how I proceeded, verbatim:
```
$ wget -q -O spiped-1.5.0.tar.gz https://github.com/Tarsnap/spiped/archive/1.5.0.tar.gz
$ tar xzf spiped-1.5.0.tar.gz
$ cd spiped-1.5.0
$ make
Makefile:5: *** missing separator.  Stop.
```

**Comment by cperciva** [comment]
$%^& stupid github.  Don't use that tarball; it's a snapshot of the git tag, without release steps applied.

Grab the 1.5.0 tarball from the spiped website: http://www.tarsnap.com/spiped.html

**Comment by zoot** [comment]
Thanks for the clarity @cperciva - I'll download from the specified URL.

I subsequently cloned from the git master branch and the build worked.

Many folks are likely to pull down the same tarball, so I'd suggest solving that issue.

Most of my build scripts pull release tarballs this way, for other software on github. I'm not completely familiar with what you're describing as being the issue. I'll investigate how github builds those tagged snapshots.

**Comment by cperciva** [comment]
It looks like the tarballs github generates automatically are just snapshots of the tree.  That works fine for some projects, but if there's a "turn this tree into a release" step then people won't necessarily get the bits they're expecting.

We reorganized the build code after 1.5.0 which is why you're now able to make the checked-out tree, but you're still not getting exactly the bits which you would get from a release -- in particular, we insert version numbers and the release date into man pages.  (In 1.5.0 days, our release-build script generated POSIX-compliant Makefiles too.)
