### ISSUE TITLE
spiped setup help with ssh

### ISSUE THREAD

**Issue by jungle-boogie** [Tarsnap/spiped#157]
Hi there,

Could you please explain how I get spiped working with ssh?
I see vague terms like "firewall off port 22", so does that mean I need to edit the `sshd_config`? I DO have sshd listening on port 8022, but that doesn't make a difference. Having it on port 22 didn't seem to connect either.

I have this process running on a computer as the server:
`spiped -d -s [0.0.0.0]:8022 -t [127.0.0.1]:22 -k /usr/local/etc/ssh/spiped.key`

Here's the client `.ssh/config` for the client:
```
Host system
ProxyCommand spipe -t %h:8022 -k ~/.ssh/spiped.key
```
Does the key name need to contain the hostname?

When I do `ssh system`, this is what I see:
`ssh_exchange_identification: Connection closed by remote host`

Running git master on both machines. One is freebsd 11.1 and another is ubuntu-like.

client ssh:  `OpenSSH_7.4p1, OpenSSL 1.0.2g  1 Mar 2016`
server ssh: `OpenSSH_7.6p1, OpenSSL 1.0.2k-freebsd  26 Jan 2017`

**Comment by gperciva** [comment]
Quick thought experiment: when the client connects to the server on port 8022, which program do you want to respond?  `spiped` or `sshd`?
(it can't be both, and I'm 99% certain that if you try to run both, one will quit with a "socket already in use" message.)

There seems to be some interest in this right now, so I'll try to whip up some nice docs.  (I have a nice idea for a diagram!  :)

**Comment by cperciva** [comment]
On 01/06/18 09:59, Graham Percival wrote:
> There seems to be some interest in this right now, so I'll try to whip up some
> nice docs. (I have a nice idea for a diagram! :)

FWIW, the canonical reference for this set up is my blog post:
http://www.daemonology.net/blog/2012-08-30-protecting-sshd-using-spiped.html

But that is a bit FreeBSD-centric.

-- 
Colin Percival
Security Officer Emeritus, FreeBSD | The power to serve
Founder, Tarsnap | www.tarsnap.com | Online backups for the truly paranoid

**Comment by jungle-boogie** [comment]
Okay, I think my mistake was changing the port sshd is listening on AND running `spiped` on that same port.
I do believe I read Colin's post. It seemed very easy, but I wasn't understanding it completely.

I found this page and I think this is where my head started spinning:
https://www.vultr.com/docs/protect-ssh-access-using-spiped-on-openbsd

I am still confused by this sentence on your blog, @cperciva:
> By running spiped on a server, configured to accept connections on port 8022 and connect to port 22 on the same host, it becomes possible to firewall off port tcp/22 completely and yet still be able to connect over SSH from anywhere in the world — as long as you have the spiped secret key, of course.

Are you saying close port 22 on the firewall, open up 8022 and use `spipe` with the key to connect to that machine?

**Comment by gperciva** [comment]
Yes, port 22 should be closed.  8022 should be open.  You should use `spiped` (note the `d`) to set up a tunnel.

... I'll upload a crappy version of my diagram within the next two hours.  (I got hung up on improving the fonts, but that isn't necessary for the first draft.)

**Comment by gperciva** [comment]
quick correction: I was wrong about using the `d` for the client-server connection.  Sorry!  I discovered this while double-checking the diagram.

**Comment by gperciva** [comment]
Hi @jungle-boogie,

Here's a horrible first draft (not yet seen by @cperciva):
![bad-spiped-ssh](https://user-images.githubusercontent.com/222157/34647121-9fb34e26-f32e-11e7-8dbd-5dfa01c85192.png)
- Black are permanent items (computers, services which are running 24/7).
- Blue is the command you run when you want to connect.
- Purple is an automatic command which is called by ssh's `ProxyCommand`.

Also, if the port is `0.0.0.0`, that means that it's listening to everything (and the firewall is open).  If it's `127.0.0.1`, then it only listens to localhost (and the firewall should be closed on that port).

(I'm hoping to make this an xkcd-style diagram, since that drawing style automatically inspires confidence and trust.  But matplotlib was *not* the right tool for this task -- or at least, virtually none of my knowledge of pgf/tikz transferred over to matplotlib.  Oh well, I can clean it up tomorrow.  :)

**Comment by jungle-boogie** [comment]
Nice illustration, it does help. Are you sure `spiped` is used? I think `spipe` is the client, which usues the `ProxyCommand`.

**Comment by cperciva** [comment]
When using the ProxyCommand approach, yes, it's `spipe`, not `spiped` which gets run.  Also, in that case `ssh` is not connecting to port 8022 (or any other port) locally -- it's communicating with spipe over a unix pipe.

**Comment by gperciva** [comment]
@jungle-boogie you're right; it's not `spiped` between the computers.  I actually noted this in an earlier post https://github.com/Tarsnap/spiped/issues/157#issuecomment-355799728
but I still wrote the wrong thing in the first draft of the diagram.  :(

**Comment by jungle-boogie** [comment]
While port 8022 is open on the firewall to allow access to your machines externally via `spiped`, do you take precautions and setup a firewall on port 8022?

**Comment by gperciva** [comment]
@jungle-boogie should the second 8022 be 22?

If you don't want to the server to provide access to other resources (say, port 80 for http traffic), then you'd close off every port other than 8022.  You could still have a firewall monitor that port (such as only allowing connections from certain IPs [*], keeping logs, etc.).

[*] that wouldn't work if you travel, of course.  One of the original motivations for writing spiped was so that the author could keep port 8022 available anywhere, since he wouldn't know what IP he'd have at a BSD conference, airport lounge, etc.

**Comment by jungle-boogie** [comment]
Hi @gperciva,

In this case, I mean 8022 for both in my question above. I do feel more comfortable leaving port 8022 open (over 22), but then I need to make sure I always have the key. ;)

Thanks for your diagram. I do hope you make another revision, I think it would help explain ssh/spiped and the general purpose of spiped in general.

**Comment by jungle-boogie** [comment]
And thanks to your brother (?) @cperciva  for spiped!

**Comment by gperciva** [comment]
@jungle-boogie yes, I'm still working on the image in preparation for it being added to the main README.  And yes, Colin is my younger brother.  :)
