### ISSUE TITLE
Question regarding the max connections being capped at 500

### ISSUE THREAD

**Issue by Jaymon** [Tarsnap/spiped#24]
We keep open connections between 2 machines for some long running processes and are bumping up against the 500 connection limit.

Before I forked the code to remove the 500 connection limit, I thought I would ask if there was a particular reason behind the limit to begin with so I'm not re-learning lessons you have already learned?

Thanks for any help and guidance :)

**Comment by cperciva** [comment]
spiped uses libcperciva's events system, which uses select, which is limited to file descriptors up to FD_SETSIZE (often 1024).  Since each spiped connection involves two sockets, 500 connections is roughly the limit on what you can handle.

So you probably want to be submitting a patch which changes libcperciva/events/events_network.c from using select to using poll. :-)

**Comment by Jaymon** [comment]
Thank you so much for the guidance, you've saved me hours of pain!

**Comment by cperciva** [comment]
Is this something (switching libcperciva to using poll) which you're interested in doing?  It's a change I would be very happy to accept (subject to the code being correct and stylish).

**Comment by Jaymon** [comment]
Doh, sorry I went dark and missed your question, problem with a Github notifications setting that I fixed last night.

We're absolutely interested in making this change. Not gonna lie though, low level C networking is a little outside my wheelhouse so this could take me a while. We've mitigated the problem somewhat on our end by being more aggressive with timeouts and reconnections but we'll eventually have to either address this issue head on or switch spiped out of our stack, which would prefer not to do.

I'll keep you updated, and thanks for opening the issue on libcperciva.

**Comment by cperciva** [comment]
No worries, I figured that the important thing was to have the libcperciva issue open so that someone -- whether you or someone else -- could see what needed to be done.

Depending on your time/money balance you may want to hire someone to handle this; it should be fairly straightforward.  Let me know if you need help.

**Comment by cperciva** [comment]
In case you still care about this: #112 should fix this problem.

**Comment by Jaymon** [comment]
This is so great! We have been working around this issue with the idea that we would eventually tackle it ourselves but it kept getting pushed down our todo list, I'm glad to see this change :)
